// sites/tomekf/src/components/Input.tsx
import { clsx } from 'clsx';
import type { Component, JSX } from 'solid-js';

const Input: Component<JSX.InputHTMLAttributes<HTMLInputElement>> = ({
    readonly,
    ...restProps
}) => {
    return (
        <input
            class={clsx(
                'text-black shadow appearance-none border rounded p-2',
                {
                    'bg-neutral-400': readonly,
                },
            )}
            readonly={readonly || false}
            type="text"
            {...restProps}
        />
    );
};

export default Input;

// pocs/react-playground/src/components/Input/Input.tsx
import { clsx } from 'clsx';

const Input = ({
    readOnly,
    ...restProps
}: React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) => {
    return (
        <input
            className={clsx('text-black shadow appearance-none border rounded p-2', {
                'bg-gray-400': readOnly,
            })}
            readOnly={readOnly}
            type="text"
            {...restProps}
        />
    );
};

export default Input;
