// apps/react-playground/src/components/Input/Input.tsx
import classnames from 'classnames';

const Input = ({
  readOnly,
  ...restProps
}: React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>) => {
  return (
    <input
      className={classnames('text-black shadow appearance-none border rounded p-2', {
        'bg-gray-400': readOnly,
      })}
      readOnly={readOnly}
      type="text"
      {...restProps}
    />
  );
};

export default Input;

// pocs/astro-solidjs/src/components/Input.tsx
import type { Component, JSX } from 'solid-js';
import { twMerge } from 'tailwind-merge';

// Component<Props> or just (props: Props)
const Input: Component<JSX.InputHTMLAttributes<HTMLInputElement>> = (props) => {
    return (
        <input
            class={twMerge(
                'rounded-md bg-violet-900 p-3 mt-8',
                props.readonly && 'bg-gray-400',
            )}
            type="text"
            {...props}
        />
    );
};

export default Input;
